<?php
include 'configRodo.php';
$connection=mysql_connect("$bdservidor","$bdunombre","$bdpass") or die("Error conectando a la base de datos");
$db=mysql_select_db("$bdnombre",$connection) or die ("Error seleccionando la base de datos");
				
$query  = "SELECT id, name, content FROM upload";
$result = mysql_query($query) or die('Error, query failed');
?>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<title>Ejemplo jQueryUI + Imagen Lepra</title>
		<link type="text/css" href="include/jquery-ui-1.8.14.custom/css/cupertino/jquery-ui-1.8.14.custom.css" rel="stylesheet" />	
		<script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
		<script type="text/javascript" src="include/jquery-ui-1.8.14.custom/js/jquery-ui-1.8.14.custom.min.js"></script>
		<script type="text/javascript">
			$(function(){	

				// Dialog			
				$('#dialog').dialog({
					autoOpen: false,
					width: 450,
					/*buttons: {
						"Cargar imagen": function() { 
							$(this).dialog("close"); 
						}, 
						"Cancel": function() { 
							$(this).dialog("close"); 
						} 
					}*/
				});
				
				// Dialog Link
				$('#dialog_link').click(function(){
					$('#dialog').dialog('open');
					return false;
				});
				
			});
		</script>
		<style type="text/css">
			/*demo page css*/
			body{ font: 62.5% "Trebuchet MS", sans-serif; margin: 50px;}
			.demoHeaders { margin-top: 2em; }
			#dialog_link {padding: .4em 1em .4em 20px;text-decoration: none;position: relative;}
			#dialog_link span.ui-icon {margin: 0 5px 0 0;position: absolute;left: .2em;top: 50%;margin-top: -8px;}
			ul#icons {margin: 0; padding: 0;}
			ul#icons li {margin: 2px; position: relative; padding: 4px 0; cursor: pointer; float: left;  list-style: none;}
			ul#icons span.ui-icon {float: left; margin: 0 4px;}
		</style>	
	</head>
	<body>
	<h1>Ejemplo jQueryUI + Imagen Lepra</h1>

	<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
	<h2 class="demoHeaders">Dialog</h2>
		<p><a href="#" id="dialog_link" class="ui-state-default ui-corner-all"><span class="ui-icon ui-icon-newwin"></span>Ver Imagen</a></p>
	<!-- ui-dialog -->
		<div id="dialog" title="Ver Imagen">
			<?php
				if(mysql_num_rows($result) == 0)				{
					echo "No hay imagen <br>";
					if(isset($_POST['upload']))
					{
							$fileName = $_FILES['userfile']['name'];
							$tmpName  = $_FILES['userfile']['tmp_name'];
							$fileSize = $_FILES['userfile']['size'];
							$fileType = $_FILES['userfile']['type'];
							
							$fp = fopen($tmpName, 'r');
							$content = fread($fp, $fileSize);
							$content = addslashes($content);
							fclose($fp);
							
							if(!get_magic_quotes_gpc())
							{
								$fileName = addslashes($fileName);
							}
							
							//$connection=mysql_connect("$bdservidor","$bdunombre","$bdpass") or die("Error conectando a la base de datos");
							//$db=mysql_select_db("$bdnombre",$connection) or die ("Error seleccionando la base de datos");
							
							$insertar = "INSERT INTO upload (name, size, type, content ) VALUES ('$fileName', '$fileSize', '$fileType', '$content')";
					
							mysql_query($insertar) or die('Error, query failed');                    
									
							echo "<br>La imagen ".$fileName." se ha cargado<br>";
					}        
					?>
					<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data" name="uploadform">
					  <table width="350" border="0" cellpadding="1" cellspacing="1" class="box">
						<tr> 
						  <td width="246"><input type="hidden" name="MAX_FILE_SIZE" value="2000000"><input name="userfile" type="file" class="box" id="userfile">
							 </td>
						  <td width="80"><input name="upload" type="submit" class="box" id="upload" value="Upload"></td>
						</tr>
					  </table>
					</form>
				<?php
				} 
				else
				{
				while(list($id, $name) = mysql_fetch_array($result))
				{
				?>
					<img id="<?php echo $id; ?>" src="download.php?id=<?php echo $id; ?> alt="<?php echo $name; ?>" />
				<?php
				echo "<br>"; 
				echo "Nombre: ".$name; 
				echo "<br>";        
				}
			}
			?>
		</div>
	</body>
</html>